localisation_ru = {
    # MESSAGES
    'HELLO': 'Я бот-помощник.\nЧто я могу для вас сделать ?\n\n',
    'WHATSEARCH': 'Пожалуйста, введите строку для поиска:',
    'NOTFOUND': 'Простите, по вашему запросу ничего не найдено',
    'MORE': 'Ещё результаты',
    'SENDINGPDF': 'Высылаю PDF-файл с программой конференции',
    'WHICHDAY': 'Какой день вас интересует ?\n\n',
    'CHOOSESECTION': 'Выберите секцию: \n\n',
    'CHOOSETIME': 'Выберите время: \n\n',
    'WRONG': 'Я вас не понимаю.',
    'GOODBYE': 'До свидания!',
    'FEEDBACKMESSAGE': 'Здесь можно оставить обратную связь для разработчиков бота:',
    'FEEDBACKTHANKYOU': 'Cпасибо, что помогаете сделать бота лучше!',
    'CONFLICTMESSAGE': 'Эти доклады пересекаются по времени:',
    'NOTIFICATIONADDED': '<b>Вам придёт сообщение за десять минут до доклада:</b>\n',
    'NOTIFICATIONREMOVED': '<b>Уведомление отменено.</b>',
    # BUTTONS
    'SHOWPROGRAM': 'Показать программу по секциям',
    'SHOWPROGRAMTIME': 'Показать программу по времени',
    'SENDPROGRAM': 'Прислать программу в PDF',
    'SEARCHPROGRAM': 'Найти доклад или автора',
    'LANGUAGE': 'English',
    'TOBEGINNING': 'В начало',
    'BACK': 'Назад',
    '24': '24 сентября',
    '25': '25 сентября',
    'FEEDBACK': 'Оставить фидбек',
    'MARKED': 'Отмеченные доклады',
    'CONFLICTS': 'Пересечения',
    # SECTIONS
    'PLENARY': 'Пленарная секция',
    'RESEARCH': 'Исследовательская секция',
    'YOUNG': 'Конференция молодых учёных',
    'WORKSHOPS': 'Семинары, воркошопы, мастер-классы',
    'FOOD': 'Еда',
    'DETAILS': 'Подробнее: ',
}
localisation_en = {
    # MESSAGES
    'HELLO': 'I am a helper bot.\nWhat can I do for you?\n\n',
    'WHATSEARCH': 'Please, enter what do you want to search for:',
    'NOTFOUND': 'Sorry, no results found for your request',
    'MORE': 'More results',
    'SENDINGPDF': 'Sending program as a PDF-file',
    'WHICHDAY': 'Which date ?\n\n',
    'CHOOSESECTION': 'Choose section: \n\n',
    'CHOOSETIME': 'Choose time: \n\n',
    'GOODBYE': 'Goodbye!',
    'WRONG': "I don't understand you",
    'FEEDBACKMESSAGE': 'You can leave feedback for bot developers here:',
    'FEEDBACKTHANKYOU': 'Thank you for helping to make this bot better!',
    'CONFLICTMESSAGE': 'This talks have time conflicts:',
    'NOTIFICATIONADDED': '<b>You will recieve a message 10 minutes before the talk:</b>\n',
    'NOTIFICATIONREMOVED': '<b>Notification cancelled</b>.',

    # BUTTONS
    'SHOWPROGRAM': 'Show the conference program',
    'SHOWPROGRAMTIME': 'Show program by time',
    'SENDPROGRAM': 'Send the program as PDF',
    'SEARCHPROGRAM': 'Find presentation or speaker',
    'LANGUAGE': 'Русский',
    'TOBEGINNING': 'To beginning',
    'BACK': 'Back',
    '24': '24 September',
    '25': '25 September',
    'FEEDBACK': 'Leave feedback',
    'MARKED': 'Marked talks',
    'CONFLICTS': 'Conflicts',
    # SECTIONS
    'PLENARY': 'Plenary session',
    'RESEARCH': 'Research Papers Session',
    'YOUNG': 'PhD and student showcase',
    'WORKSHOPS': 'Workshops, seminars, master-classes',
    'FOOD': 'Food',
    'DETAILS': 'Details: ',
}
